AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
LineLength:
  Max: 120
ClassVars:
  Enabled: false
MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Performance/RegexpMatch:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
