AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
LineLength:
  Max: 120
ClassVars:
  Enabled: false
MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Performance/RegexpMatch:
  Enabled: false
Style/SafeNavigation:
  Enabled: false # Temporarily disabled due to bug: https://github.com/bbatsov/rubocop/issues/4741
Lint/UriEscapeUnescape:
  Enabled: false
